title: FaveShade
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://faveshade.com
# tagManagerCode: GTM-W53GM9S
# googleAdClient: ca-pub-5576042369154755
themeColor: "#8308E0"

googleFonts:
  - Nunito
  - Comfortaa
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:path

sass:
  style: compressed

plugins:
  - jekyll-sitemap