title: FaveShade
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://faveshade.com
tagManagerCode: GTM-NZXPPP4
# googleAdClient: ca-pub-5576042369154755
themeColor: "#8308E0"

googleFonts:
  - Nunito:400,700
  - Comfortaa